version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  portfolio:
    build: ./portfolio
    ports:
      - "8080:80"
    depends_on:
      - api
    restart: unless-stopped